import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * Conditional class names with Tailwind conflict resolution.
 *
 * `clsx` alone would leave `px-2 px-4` both in the string and let source order in
 * the stylesheet decide the winner; `twMerge` keeps the last one. Shadcn/UI
 * components generated by the CLI import this exact symbol from `@/lib/utils`,
 * which is why the path and name are fixed.
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
